### ISSUE TITLE
Support devnet-6

### ISSUE THREAD

**Issue by qzhodl** [Inphi/blob-utils#11]
As Jimmy Chen pointed out [here](https://hackmd.io/@jimmygchen/H1XUtBIfn), may need to update to support devnet-6

**Comment by Inphi** [comment]
hey @qzhodl. For the time being, please use the [nethermind script](https://github.com/NethermindEth/nethermind/tree/feature/send-blobs-tool/src/Nethermind/Nethermind.SendBlobs) that Jimmy pointed out. I haven't had time to keep track of EIP-4844 development these days and it may be a while before I can update this.

I'll happily take PRs to add devnet-6 support though.

**Comment by Inphi** [comment]
done via #12
