### ISSUE TITLE
send tx failed: Invalid

### ISSUE THREAD

**Issue by kushagra2jindal** [Inphi/blob-utils#13]
I am trying to use testnet 7 and send a blob, but tx keeps on failing with this error 2023/07/16 12:57:01 send tx failed: Invalid. Can someone help me with a reason?

```shell
./blob-utils tx --rpc-url https://rpc.4844-devnet-7.ethpandaops.io \
    --blob-file <(echo hello) \
    --to 0xC8D369B164361A8961286CFbaB3bc10F962185a8 \
    --private-key <mykey> \
    --gas-limit 210000 \
    --chain-id 7011893055 \
    --priority-gas-price 200000000 \
    --max-fee-per-data-gas 300000000
``` 

The wallet address I am using is 0x6Fb447Ae94F5180254D436A693907a1f57696900

**Comment by Inphi** [comment]
I haven't been keeping up to date with spec changes and blob-utils hasn't been maintained well. But it should be working for devnet-7 now.

**Comment by Inphi** [comment]
Closing. This should be working on the latest devnet.
