### ISSUE TITLE
invalid blob 0: can't verify opening proof

### ISSUE THREAD

**Issue by koloz193** [Inphi/blob-utils#18]
i seem to be getting the same error both when i submit a blob txn locally and against devnet 12

```
./blob-utils tx \
    --rpc-url https://rpc.dencun-devnet-12.ethpandaops.io \
    --blob-file <(echo hello) \
    --to 0x3Af4A1fe34392AACbf4cDA98518860b9Ea3c8929 \
    --private-key <pk> \
    --gas-limit 210000 \
    --chain-id 7011893062 \
    --priority-gas-price 200000000 \
    --max-fee-per-blob-gas 300000000
```

`2023/12/14 21:53:00 failed to send transaction: invalid blob 0: can't verify opening proof`

**Comment by lyfsn** [comment]
@koloz193 Hello, have you solved this problem? How did you solve it?

**Comment by koloz193** [comment]
@lyfsn yea i ended up using this [fork](https://github.com/PabloCastellano/blob-utils) which has been updated to support the newer devnets

**Comment by Inphi** [comment]
It should be fixed on master now. Let me know if that works.

**Comment by koloz193** [comment]
Yup looks like it works now. Closing issue
